---
base_dir: results
log_level: INFO
data:
  batch_size: 32
  dataset_dir: ../data/PEMS_traffic_volume
  test_batch_size: 64
  val_batch_size: 64

model:
  cl_decay_steps: 2000
  horizon: 12
  input_dim: 1
  l1_decay: 0 # not using
  num_nodes: 150
  num_rnn_layers: 1 # 2 # number of hidden layers in RNN
  output_dim: 1
  rnn_units: 128 # hidden unit dimension
  seq_len: 12
  use_curriculum_learning: true

train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 300
  epsilon: 1.0e-3
  global_step: 0
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps: [20] # , 30, 40, 50
  test_every_n_epochs: 1
  preds_file: "GCGRNN_volume_150.csv"
  groundtruth_file: "y_truth_GCGRNN_volume_150.csv" 
